-- MySQL Script generated by MySQL Workbench
-- Fri Sep 23 18:23:55 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema mecanica
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mecanica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mecanica` DEFAULT CHARACTER SET utf8 ;
USE `mecanica` ;

-- -----------------------------------------------------
-- Table `mecanica`.`Valor mao de obra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mecanica`.`Valor mao de obra` (
  `idValor mao de obra` INT NOT NULL,
  `valor_serviço` VARCHAR(45) NULL,
  `peças_utilizada` VARCHAR(45) NULL,
  `descrição_executada` VARCHAR(45) NULL,
  `valor_total` VARCHAR(45) NULL,
  `valor_mao_obra` VARCHAR(45) NULL,
  PRIMARY KEY (`idValor mao de obra`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mecanica`.`Veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mecanica`.`Veiculo` (
  `idVeiculo` INT NOT NULL,
  `Tipo_veiculo` VARCHAR(45) NULL,
  `Cor_veiculo` VARCHAR(45) NULL,
  `Ano_veiculo` VARCHAR(45) NULL,
  `Modelo_veiculo` VARCHAR(45) NULL,
  `fabricante` VARCHAR(45) NULL,
  `descrição` VARCHAR(45) NULL,
  `Valor mao de obra_idValor mao de obra` INT NOT NULL,
  PRIMARY KEY (`idVeiculo`, `Valor mao de obra_idValor mao de obra`),
  INDEX `fk_Veiculo_Valor mao de obra1_idx` (`Valor mao de obra_idValor mao de obra` ASC) VISIBLE,
  CONSTRAINT `fk_Veiculo_Valor mao de obra1`
    FOREIGN KEY (`Valor mao de obra_idValor mao de obra`)
    REFERENCES `mecanica`.`Valor mao de obra` (`idValor mao de obra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mecanica`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mecanica`.`Cliente` (
  `idCliente` INT NOT NULL,
  `Veiculo_idVeiculo` INT NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `Endereço` VARCHAR(45) NULL,
  `telefone` VARCHAR(45) NULL,
  `cidade` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  `cpf` INT NULL,
  PRIMARY KEY (`idCliente`, `Veiculo_idVeiculo`),
  INDEX `fk_Cliente_Veiculo_idx` (`Veiculo_idVeiculo` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_Veiculo`
    FOREIGN KEY (`Veiculo_idVeiculo`)
    REFERENCES `mecanica`.`Veiculo` (`idVeiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mecanica`.`Finalizado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mecanica`.`Finalizado` (
  `idFinalizado` INT NOT NULL,
  PRIMARY KEY (`idFinalizado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mecanica`.`Mecanico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mecanica`.`Mecanico` (
  `idMecanico` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `endereço` VARCHAR(45) NULL,
  `especialidade` VARCHAR(45) NULL,
  `Finalizado_idFinalizado` INT NOT NULL,
  PRIMARY KEY (`idMecanico`, `Finalizado_idFinalizado`),
  INDEX `fk_Mecanico_Finalizado1_idx` (`Finalizado_idFinalizado` ASC) VISIBLE,
  CONSTRAINT `fk_Mecanico_Finalizado1`
    FOREIGN KEY (`Finalizado_idFinalizado`)
    REFERENCES `mecanica`.`Finalizado` (`idFinalizado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mecanica`.`Peças`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mecanica`.`Peças` (
  `idPeças` INT NOT NULL,
  `01` VARCHAR(45) NULL,
  `02` VARCHAR(45) NULL,
  `03` VARCHAR(45) NULL,
  `04` VARCHAR(45) NULL,
  `05` VARCHAR(45) NULL,
  PRIMARY KEY (`idPeças`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mecanica`.`estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mecanica`.`estoque` (
  `idestoque` INT NOT NULL,
  `Peças_idPeças` INT NOT NULL,
  PRIMARY KEY (`idestoque`, `Peças_idPeças`),
  INDEX `fk_estoque_Peças1_idx` (`Peças_idPeças` ASC) VISIBLE,
  CONSTRAINT `fk_estoque_Peças1`
    FOREIGN KEY (`Peças_idPeças`)
    REFERENCES `mecanica`.`Peças` (`idPeças`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mecanica`.`Ordem de serviço`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mecanica`.`Ordem de serviço` (
  `idOrdem de serviço` INT NOT NULL,
  `data_emissao` VARCHAR(45) NULL,
  `valor` VARCHAR(45) NULL,
  `status_serviço` VARCHAR(45) NULL,
  `data_finalização` VARCHAR(45) NULL,
  PRIMARY KEY (`idOrdem de serviço`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mecanica`.`Serviço`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mecanica`.`Serviço` (
  `idServiço` INT NOT NULL,
  `Tipo_serviço` VARCHAR(45) NULL,
  `escolha_serviço` TINYINT NULL,
  `valor_serviço` VARCHAR(45) NULL,
  `Ordem de serviço_idOrdem de serviço` INT NOT NULL,
  PRIMARY KEY (`idServiço`, `Ordem de serviço_idOrdem de serviço`),
  INDEX `fk_Serviço_Ordem de serviço1_idx` (`Ordem de serviço_idOrdem de serviço` ASC) VISIBLE,
  CONSTRAINT `fk_Serviço_Ordem de serviço1`
    FOREIGN KEY (`Ordem de serviço_idOrdem de serviço`)
    REFERENCES `mecanica`.`Ordem de serviço` (`idOrdem de serviço`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mecanica`.`Cliente solicita serviço`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mecanica`.`Cliente solicita serviço` (
  `Serviço_idServiço` INT NOT NULL,
  `Cliente_idCliente` INT NOT NULL,
  `Cliente_Veiculo_idVeiculo` INT NOT NULL,
  PRIMARY KEY (`Serviço_idServiço`, `Cliente_idCliente`, `Cliente_Veiculo_idVeiculo`),
  INDEX `fk_Serviço_has_Cliente_Cliente1_idx` (`Cliente_idCliente` ASC, `Cliente_Veiculo_idVeiculo` ASC) VISIBLE,
  INDEX `fk_Serviço_has_Cliente_Serviço1_idx` (`Serviço_idServiço` ASC) VISIBLE,
  CONSTRAINT `fk_Serviço_has_Cliente_Serviço1`
    FOREIGN KEY (`Serviço_idServiço`)
    REFERENCES `mecanica`.`Serviço` (`idServiço`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Serviço_has_Cliente_Cliente1`
    FOREIGN KEY (`Cliente_idCliente` , `Cliente_Veiculo_idVeiculo`)
    REFERENCES `mecanica`.`Cliente` (`idCliente` , `Veiculo_idVeiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mecanica`.`Cliente escolha serviço`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mecanica`.`Cliente escolha serviço` (
  `Cliente_idCliente` INT NOT NULL,
  `Cliente_Veiculo_idVeiculo` INT NOT NULL,
  `Serviço_idServiço` INT NOT NULL,
  PRIMARY KEY (`Cliente_idCliente`, `Cliente_Veiculo_idVeiculo`, `Serviço_idServiço`),
  INDEX `fk_Cliente_has_Serviço_Serviço1_idx` (`Serviço_idServiço` ASC) VISIBLE,
  INDEX `fk_Cliente_has_Serviço_Cliente1_idx` (`Cliente_idCliente` ASC, `Cliente_Veiculo_idVeiculo` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_has_Serviço_Cliente1`
    FOREIGN KEY (`Cliente_idCliente` , `Cliente_Veiculo_idVeiculo`)
    REFERENCES `mecanica`.`Cliente` (`idCliente` , `Veiculo_idVeiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cliente_has_Serviço_Serviço1`
    FOREIGN KEY (`Serviço_idServiço`)
    REFERENCES `mecanica`.`Serviço` (`idServiço`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mecanica`.`Escolha da especialidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mecanica`.`Escolha da especialidade` (
  `Ordem de serviço_idOrdem de serviço` INT NOT NULL,
  `Mecanico_idMecanico` INT NOT NULL,
  PRIMARY KEY (`Ordem de serviço_idOrdem de serviço`, `Mecanico_idMecanico`),
  INDEX `fk_Ordem de serviço_has_Mecanico_Mecanico1_idx` (`Mecanico_idMecanico` ASC) VISIBLE,
  INDEX `fk_Ordem de serviço_has_Mecanico_Ordem de serviço1_idx` (`Ordem de serviço_idOrdem de serviço` ASC) VISIBLE,
  CONSTRAINT `fk_Ordem de serviço_has_Mecanico_Ordem de serviço1`
    FOREIGN KEY (`Ordem de serviço_idOrdem de serviço`)
    REFERENCES `mecanica`.`Ordem de serviço` (`idOrdem de serviço`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ordem de serviço_has_Mecanico_Mecanico1`
    FOREIGN KEY (`Mecanico_idMecanico`)
    REFERENCES `mecanica`.`Mecanico` (`idMecanico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mecanica`.`Analisa veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mecanica`.`Analisa veiculo` (
  `Veiculo_idVeiculo` INT NOT NULL,
  `Mecanico_idMecanico` INT NOT NULL,
  `identificação` VARCHAR(45) NULL,
  `descrição` VARCHAR(45) NULL,
  `materia prima` VARCHAR(45) NULL,
  `valor_peças` VARCHAR(45) NULL,
  `valor_mao_obra` VARCHAR(45) NULL,
  PRIMARY KEY (`Veiculo_idVeiculo`, `Mecanico_idMecanico`),
  INDEX `fk_Veiculo_has_Mecanico_Mecanico1_idx` (`Mecanico_idMecanico` ASC) VISIBLE,
  INDEX `fk_Veiculo_has_Mecanico_Veiculo1_idx` (`Veiculo_idVeiculo` ASC) VISIBLE,
  CONSTRAINT `fk_Veiculo_has_Mecanico_Veiculo1`
    FOREIGN KEY (`Veiculo_idVeiculo`)
    REFERENCES `mecanica`.`Veiculo` (`idVeiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Veiculo_has_Mecanico_Mecanico1`
    FOREIGN KEY (`Mecanico_idMecanico`)
    REFERENCES `mecanica`.`Mecanico` (`idMecanico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mecanica`.`Mecanico_has_Valor mao de obra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mecanica`.`Mecanico_has_Valor mao de obra` (
  `Mecanico_idMecanico` INT NOT NULL,
  `Valor mao de obra_idValor mao de obra` INT NOT NULL,
  PRIMARY KEY (`Mecanico_idMecanico`, `Valor mao de obra_idValor mao de obra`),
  INDEX `fk_Mecanico_has_Valor mao de obra_Valor mao de obra1_idx` (`Valor mao de obra_idValor mao de obra` ASC) VISIBLE,
  INDEX `fk_Mecanico_has_Valor mao de obra_Mecanico1_idx` (`Mecanico_idMecanico` ASC) VISIBLE,
  CONSTRAINT `fk_Mecanico_has_Valor mao de obra_Mecanico1`
    FOREIGN KEY (`Mecanico_idMecanico`)
    REFERENCES `mecanica`.`Mecanico` (`idMecanico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Mecanico_has_Valor mao de obra_Valor mao de obra1`
    FOREIGN KEY (`Valor mao de obra_idValor mao de obra`)
    REFERENCES `mecanica`.`Valor mao de obra` (`idValor mao de obra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mecanica`.`Mecanico_has_estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mecanica`.`Mecanico_has_estoque` (
  `Mecanico_idMecanico` INT NOT NULL,
  `estoque_idestoque` INT NOT NULL,
  PRIMARY KEY (`Mecanico_idMecanico`, `estoque_idestoque`),
  INDEX `fk_Mecanico_has_estoque_estoque1_idx` (`estoque_idestoque` ASC) VISIBLE,
  INDEX `fk_Mecanico_has_estoque_Mecanico1_idx` (`Mecanico_idMecanico` ASC) VISIBLE,
  CONSTRAINT `fk_Mecanico_has_estoque_Mecanico1`
    FOREIGN KEY (`Mecanico_idMecanico`)
    REFERENCES `mecanica`.`Mecanico` (`idMecanico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Mecanico_has_estoque_estoque1`
    FOREIGN KEY (`estoque_idestoque`)
    REFERENCES `mecanica`.`estoque` (`idestoque`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


